### ISSUE TITLE
3 extra blank lines at the end of stacktrace

### ISSUE THREAD

**Issue by singularitti** [jkrumbiegel/ClearStacktrace.jl#5]
I am running 0.2.1 now. It looks like 3 extra blank lines will be printed at the end of a stacktrace. I guess it would have to do with those ones the un-printed 3 frames mentioned [here](https://github.com/JuliaLang/julia/issues/36026#issuecomment-637017582).

![image](https://user-images.githubusercontent.com/25192197/83514522-cf21a500-a4a1-11ea-87bd-e65f6600ac5b.png)

```julia
julia> versioninfo()
Julia Version 1.5.0-beta1.0
Commit 6443f6c95a (2020-05-28 17:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by jkrumbiegel** [comment]
ah yeah I was just printing after every loop, I'll omit the last one. Good point!

**Comment by jkrumbiegel** [comment]
fixed https://github.com/jkrumbiegel/ClearStacktrace.jl/commit/39626b56d6e2145d9c7901340006f09535afddcb
